# Generated by Django 6.0.4 on 2026-04-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_id', models.IntegerField(blank=True, db_column='workflow_id', null=True)),
                ('step_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('sla_status', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_role_id', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflows_taskinstance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.IntegerField(db_column='workflow_id')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflows_workflowinstance',
                'managed': False,
            },
        ),
    ]
