# Generated by Django 6.0.4 on 2026-04-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskinstance',
            table='analytics_task_instance',
        ),
        migrations.AlterModelTable(
            name='workflowinstance',
            table='analytics_workflow_instance',
        ),
    ]
