# Generated by Django 6.0.4 on 2026-05-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_taskinstance_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('definition', models.TextField()),
            ],
            options={
                'db_table': 'analytics_workflow',
                'managed': False,
            },
        ),
    ]
