# Generated by Django 6.0.4 on 2026-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_bottleneckscoreweights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'analytics_permission',
                'managed': False,
            },
        ),
    ]
