# Generated by Django 6.0.4 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_summary',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
    ]
