# Generated by Django 6.0.4 on 2026-08-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_provider', models.CharField(choices=[('gemini', 'gemini'), ('ollama', 'ollama')], default='gemini', max_length=20)),
                ('ollama_model', models.CharField(default='llama3', max_length=100)),
                ('ollama_base_url', models.CharField(default='http://localhost:11434', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_config',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('workflow', 'workflow'), ('document', 'document'), ('instance', 'instance')], max_length=20)),
                ('source_id', models.IntegerField()),
                ('workflow_id', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('embedding', models.JSONField()),
                ('access_flags', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_knowledge_embedding',
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id'), name='unique_chatbot_embedding_source')],
            },
        ),
    ]
