# Generated by Django 6.0.4 on 2026-04-20 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_role_add_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='approval_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='requires_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='requires_submission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='sla_exceeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='sla_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='submission_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='submission_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('approval_needed', 'Approval Needed'), ('submission_needed', 'Submission Needed'), ('sla_warning', 'SLA Warning'), ('sla_exceeded', 'SLA Exceeded'), ('workflow_completed', 'Workflow Completed'), ('workflow_rejected', 'Workflow Rejected')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflows.role')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.taskinstance')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.workflowinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
