# Generated by Django 6.0.4 on 2026-04-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_taskinstance_approval_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
