# Generated by Django 6.0.4 on 2026-05-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_remove_user_department_role_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('widget_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('min_width', models.IntegerField(default=2)),
                ('max_width', models.IntegerField(default=6)),
                ('min_height', models.IntegerField(default=2)),
                ('max_height', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='user.role')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='dashboard.dashboard')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.widget')),
            ],
            options={
                'unique_together': {('dashboard', 'widget')},
            },
        ),
        migrations.CreateModel(
            name='WidgetPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.permission')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.widget')),
            ],
            options={
                'unique_together': {('widget', 'permission')},
            },
        ),
    ]
