# Generated by Django 6.0.4 on 2026-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='category',
            field=models.CharField(default='workflow', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='category',
            field=models.CharField(default='workflow', max_length=100),
            preserve_default=False,
        ),
    ]
