# Generated by Django 6.0.4 on 2026-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardwidget_category_widget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='widget_code',
            field=models.CharField(default='W001', max_length=50),
            preserve_default=False,
        ),
    ]
