# Generated by Django 5.2.13 on 2026-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionData',
            fields=[
                ('permission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleData',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRolePermissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_rolepermission',
                'managed': False,
            },
        ),
    ]
