# Generated by Django 5.2.13 on 2026-04-16 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('DOCUMENT_VIEWED', 'Document Viewed'), ('DOCUMENT_ACCESS_DENIED', 'Unauthorized Document Access'), ('ACTION_TAKEN', 'Workflow Action Taken'), ('COMMENT_ADDED', 'Comment Added'), ('NOTIFICATION_VIEWED', 'Notifications Viewed'), ('NOTIFICATION_READ', 'Notification Marked Read')], max_length=50)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('previous_state', models.CharField(blank=True, default='', max_length=100)),
                ('new_state', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
