# Generated by Django 5.2.13 on 2026-04-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('DOCUMENT_VIEWED', 'Document Viewed'), ('DOCUMENT_ACCESS_DENIED', 'Unauthorized Document Access'), ('ACTION_TAKEN', 'Workflow Action Taken'), ('COMMENT_ADDED', 'Comment Added'), ('NOTIFICATION_VIEWED', 'Notifications Viewed'), ('NOTIFICATION_READ', 'Notification Marked Read'), ('NOTIFICATION_RULE_CREATED', 'New Notification Rule Created'), ('NOTIFICATION_RULE_UPDATED', 'Notification Rule Edited'), ('NOTIFICATION_RULE_DELETED', 'Notification Rule Deleted'), ('NOTIFICATION_RULE_TOGGLED', 'Notification Rule Enabled/Disabled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
