# Generated by Django 6.0.4 on 2026-04-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSVImportLog',
            new_name='OneDriveSyncLog',
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('onedrive', 'OneDrive Document')], default='manual', max_length=20),
        ),
        migrations.AlterModelTable(
            name='onedrivesynclog',
            table='OneDrive_import_logs',
        ),
    ]
