# Generated by Django 6.0.4 on 2026-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_csvimportlog_onedrivesynclog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneDriveFolderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255, unique=True)),
                ('onedrive_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('workflow_id', models.IntegerField()),
                ('workflow_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onedrive_folder_mappings',
            },
        ),
    ]
