# Generated by Django 6.0.4 on 2026-04-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_onedrivefoldermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'workflows_workflow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GDriveFolderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255, unique=True)),
                ('gdrive_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('workflow_id', models.IntegerField()),
                ('workflow_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gdrive_folder_mappings',
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdrive_file_id', models.CharField(max_length=255)),
                ('drive_url', models.URLField(blank=True, max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gdrive_documents',
            },
        ),
        migrations.RenameModel(
            old_name='OneDriveSyncLog',
            new_name='GoogleDriveSyncLog',
        ),
        migrations.RemoveField(
            model_name='onedrivedocument',
            name='document',
        ),
        migrations.DeleteModel(
            name='OneDriveFolderMapping',
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('gdrive', 'Google Drive Document')], default='manual', max_length=20),
        ),
        migrations.AlterModelTable(
            name='googledrivesynclog',
            table='gdrive_import_logs',
        ),
        migrations.AddField(
            model_name='googledrivedocument',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gdrive_doc', to='documents.document'),
        ),
        migrations.DeleteModel(
            name='OneDriveDocument',
        ),
    ]
