# Generated by Django 6.0.4 on 2026-04-27 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_externalworkflow_gdrivefoldermapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('current_state', models.CharField(max_length=50)),
                ('payload', models.TextField()),
                ('runtime_state', models.TextField()),
                ('workflow_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'workflows_workflowinstance',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='gdrivefoldermapping',
            name='workflow_id',
            field=models.CharField(max_length=255),
        ),
    ]
