# Generated by Django 6.0.4 on 2026-04-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_externalworkflowinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='s3_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
