# Generated by Django 6.0.4 on 2026-04-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHoursConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField()),
                ('work_end_time', models.TimeField()),
                ('work_days', models.JSONField(default=list)),
                ('holidays', models.JSONField(default=list)),
                ('time_zone', models.CharField(default='UTC', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
