# Generated by Django 6.0.4 on 2026-04-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working_hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workinghoursconfig',
            table='working_hoursconfig',
        ),
    ]
