# process SQL generated by LLM to ensure it's safe and compatible with our DB, then execute and return results  

from .db import get_db_connection
import re #for Regular Expressions

class SQLService:

    @staticmethod
    def clean_sql(query):

        # Remove markdown
        query = re.sub(r"```sql", "", query, flags=re.IGNORECASE) 
        query = re.sub(r"```", "", query)

        # Remove semicolon
        query = query.replace(";", "")

        # Remove extra spaces/newlines
        query = query.strip()

        return query

    @staticmethod
    def validate_query(query): #if llm generates a non-SELECT or dangerous query, block it

        blocked_keywords = [
            "DELETE",
            "DROP",
            "UPDATE",
            "INSERT",
            "ALTER",
            "TRUNCATE"
        ]

        upper_query = query.upper()

        for keyword in blocked_keywords:
            if keyword in upper_query:
                raise Exception("Dangerous query detected.")

        # Allow only SELECT
        if not upper_query.startswith("SELECT"):
            raise Exception("Only SELECT queries are allowed.")

    @staticmethod
    def enforce_case_insensitive(query):

        patterns = [    #regex patterns to find column = 'value' for text search
            r"(\w+)\s*=\s*'([^']+)'"
        ]

        for pattern in patterns:
            matches = re.findall(pattern, query) #find all column = 'value' patterns

            for column, value in matches: #Replace = with LIKE
                replacement = ( 
                    f"LOWER({column}) LIKE LOWER('%{value}%')" #flexible searching with LIKE and case insensitivity
                )

                original = f"{column} = '{value}'"

                query = query.replace(original, replacement)

        return query
    
    @staticmethod
    def strip_sql_noise_words(query):
        # 1. Strip structural noise words from the question text inside the query
        noise_words = [
            r"%\s*workflow\s*%",
            r"%\s*instance\s*%",
            r"%\s*task\s*%"
        ]
        for pattern in noise_words:
            query = re.sub(pattern, "%", query, flags=re.IGNORECASE)
        
        # 2. Extract and tokenize ALL text strings inside single quotes (case-insensitive)
        # This accurately targets strings like '%PO approval invoice A%' or '%purchase order%'
        quoted_patterns = re.findall(r"'%([^']+)%'", query)
        for pattern_text in quoted_patterns:
            # Replace spaces with wildcard characters
            tokenized = pattern_text.replace(" ", "%")
            # Clean out structural duplicate wildcards
            tokenized = re.sub(r"%+", "%", tokenized)
            
            original_string = f"'%{pattern_text}%'"
            new_string = f"'%{tokenized}%'"
            query = query.replace(original_string, new_string)

        # 3. Final sanitization pass for double percentages across the entire block
        query = re.sub(r"%+", "%", query)
        return query

    @staticmethod
    def execute_query(query):

        query = SQLService.clean_sql(query)
        query = SQLService.enforce_case_insensitive(query)
        query = SQLService.strip_sql_noise_words(query)
        SQLService.validate_query(query)

        print("\nFINAL SQL:")
        print(query)

        conn = get_db_connection() #Opens a connection to MySQL database
        cursor = conn.cursor(dictionary=True) #a tool that allows us to execute SQL queries and get results as Python dictionaries instead of tuples
        cursor.execute(query) 
        results = cursor.fetchall() #Collects ALL rows returned by query and Converts them into Python list
        conn.close()

        return results