# process SQL generated by LLM to ensure it's safe and compatible with our DB, then execute and return results  

from .db import run_select_query
import re #for Regular Expressions

class SQLService:

    @staticmethod
    def extract_sql_statement(llm_response):
        """Pull a SELECT statement out of an LLM response that may (depending
        on the provider/model) wrap it in a markdown code fence and/or
        surround it with conversational text, instead of returning raw SQL
        as instructed. Returns None if no SELECT can be found, meaning the
        response should be treated as a plain greeting/answer instead."""

        # Every real query against this schema selects FROM a table -- requiring
        # a FROM clause filters out a weaker model just mentioning "a SELECT
        # query" in prose (e.g. "I'll write a SELECT query.") without ever
        # actually emitting one, which a bare "starts with SELECT" match would
        # otherwise mistake for real SQL and try to execute.
        def _looks_like_sql(candidate):
            return bool(re.search(r"\bFROM\b", candidate, re.IGNORECASE))

        # Prefer a fenced ```sql ... ``` (or bare ``` ... ```) block if present.
        fenced = re.search(r"```(?:sql)?\s*(SELECT\b.*?)```", llm_response, re.IGNORECASE | re.DOTALL)
        if fenced and _looks_like_sql(fenced.group(1)):
            return fenced.group(1).strip()

        # Otherwise, look for a bare SELECT ... statement anywhere in the text,
        # ending at the first semicolon/blank line, or the end of the text.
        bare = re.search(r"(SELECT\b.*?)(?:;|\n\s*\n|$)", llm_response, re.IGNORECASE | re.DOTALL)
        if bare and _looks_like_sql(bare.group(1)):
            return bare.group(1).strip()

        return None

    @staticmethod
    def clean_sql(query):

        # Remove markdown
        query = re.sub(r"```sql", "", query, flags=re.IGNORECASE) 
        query = re.sub(r"```", "", query)

        # Remove deletes trailing semicolons
        query = query.replace(";", "")

        query = re.sub(
                    r"(\w+)\.(lower|upper|trim)\(([^)]+)\)", 
                    r"\2(\1.\3)", 
                    query, 
                    flags=re.IGNORECASE
        )
        
        # Remove extra spaces/newlines
        query = query.strip()

        return query

    @staticmethod
    def validate_query(query): #if llm generates a non-SELECT or dangerous query, block it

        blocked_keywords = [
            "DELETE",
            "DROP",
            "UPDATE",
            "INSERT",
            "ALTER",
            "TRUNCATE"
        ]

        upper_query = query.upper() # Convert to uppercase for case-insensitive checking

        for keyword in blocked_keywords: # Check if any blocked keyword is present in the query
            if keyword in upper_query:
                raise Exception("Dangerous query detected.")

        # Allow only SELECT
        if not upper_query.startswith("SELECT"):
            raise Exception("Only SELECT queries are allowed.")

    @staticmethod
    def enforce_case_insensitive(query):

        patterns = [    #regex patterns to find column = 'value' for text search (column may be alias-qualified, e.g. awi.status)
            r"((?:\w+\.)?\w+)\s*=\s*'([^']+)'"
        ]

        for pattern in patterns:
            matches = re.findall(pattern, query) #find all column = 'value' patterns

            for column, value in matches: #Replace = with LIKE
                replacement = ( 
                    f"LOWER({column}) LIKE LOWER('%{value}%')" #flexible searching with LIKE and case insensitivity
                )

                original = f"{column} = '{value}'" #original pattern

                query = query.replace(original, replacement) #Replace original with new pattern in the query

        return query
    
    @staticmethod
    def strip_sql_noise_words(query):
        # 1. Strip structural noise words from the question text inside the query
        noise_words = [
            r"%\s*workflow\s*%",
            r"%\s*instance\s*%",
            r"%\s*task\s*%"
        ]
        for pattern in noise_words:
            query = re.sub(pattern, "%", query, flags=re.IGNORECASE)
        
        # 2. Extract and tokenize ALL text strings inside single quotes (case-insensitive)
        # This accurately targets strings like '%PO approval invoice A%' or '%purchase order%'
        quoted_patterns = re.findall(r"'%([^']+)%'", query)
        for pattern_text in quoted_patterns:
            # Replace spaces with wildcard characters
            tokenized = pattern_text.replace(" ", "%")
            # Clean out structural duplicate wildcards
            tokenized = re.sub(r"%+", "%", tokenized)
            
            original_string = f"'%{pattern_text}%'"
            new_string = f"'%{tokenized}%'"
            query = query.replace(original_string, new_string)

        # 3. remove any accidental multiple % characters that may have been introduced 
        query = re.sub(r"%+", "%", query)
        return query

    @staticmethod
    def execute_query(query):

        query = SQLService.clean_sql(query)
        query = SQLService.enforce_case_insensitive(query)
        query = SQLService.strip_sql_noise_words(query)
        SQLService.validate_query(query)

        print("\nFINAL SQL:")
        print(query)

        return run_select_query(query) #executes through Django's own DB connection (see chatbot/db.py)