# Generated by Django 6.0.4 on 2026-04-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
