# Generated by Django 6.0.4 on 2026-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='head',
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='user.RolePermission', to='user.permission'),
        ),
    ]
