# Generated by Django 5.2.13 on 2026-04-17 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_record_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_trigger', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('SLA_REMINDER', 'SLA Reminder'), ('SLA_BREACH', 'SLA Breach'), ('WORKFLOW_COMPLETED', 'Workflow Completed'), ('TASK_REJECTED', 'Task Rejected'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('COMMENT_ADDED', 'Comment Added')], max_length=50)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email Only'), ('IN_APP', 'In-App Only'), ('BOTH', 'Email + In-App')], max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
