# Generated by Django 5.2.13 on 2026-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_permission_role_rolepermission_alter_notification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email Only'), ('IN_APP_ONLY', 'In-App Only'), ('BOTH', 'Email + In-App')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_trigger',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('SLA_REMINDER', 'SLA Reminder'), ('SLA_BREACH', 'SLA Breach'), ('WORKFLOW_COMPLETED', 'Workflow Completed'), ('TASK_REJECTED', 'Task Rejected'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('COMMENT_ADDED', 'Comment Added'), ('DOCUMENT_APPROVED', 'Document Approved')], max_length=50),
        ),
    ]
