# Generated by Django 5.2.13 on 2026-04-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationrule_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, choices=[('TASK_ASSIGNED', 'Task Assigned'), ('SLA_REMINDER', 'SLA Reminder'), ('SLA_BREACH', 'SLA Breach'), ('WORKFLOW_COMPLETED', 'Workflow Completed'), ('TASK_REJECTED', 'Task Rejected'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('COMMENT_ADDED', 'Comment Added'), ('DOCUMENT_APPROVED', 'Document Approved')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Critical/Breach')], default='INFO', max_length=10),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications_inbox',
        ),
    ]
